org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.213
neo_version_range=[21,)
loader_version_range=[4,5)

## Mod Properties
mod_id=chemica
mod_name=Chemica
mod_license=MIT
mod_version=0.5.1
mod_group_id=com.cosmads.chemica

# Create and Registrate versions
create_version = 6.0.9-176
create_version_range=[6.0.9,)
ponder_version = 1.0.66
flywheel_version = 1.0.5
registrate_version = MC1.21-1.3.0+67
registrate_version_range=[1.3.0,)

 rutile_version = l3Lh7CV9

# TFMG versions
tfmg_file_id = 7430073
tfmg_version_range = [1.2.0,)

# Optional dependencies
emi_version=1.1.19+1.21.1
jei_minecraft_version = 1.21.1
jei_version = 19.25.0.322
