modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Metallurgists-of-Create/Chemica/issues"
[[mods]]
modId="chemica"
version="${file.jarVersion}"
displayName="Chemica"
displayURL="https://github.com/Metallurgists-of-Create/Chemica"
logoFile="chemica.png"
credits="Cosmads"
authors="Cosmads"
description='''

'''
[[dependencies.chemica]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.chemica]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.chemica]]
modId="tfmg"
mandatory=true
versionRange="[1.0.2c,1.1)"
ordering="AFTER"
side="BOTH"
[[dependencies.chemica]]
modId="create"
mandatory=true
versionRange="[6.0.6,)"
ordering="NONE"
side="BOTH"

[mixin]
config = "chemica.mixins.json"