modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/chemica/icon.png"
authors="cosmads"
description='''
Create & The Factory Must Grow addon expanding on chemistry & material processing
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
versionRange="${create_version_range}"
mandatory=true
ordering="AFTER"
side="BOTH"

# [[dependencies.${mod_id}]]
# modId="rutile"
# type="required"
# ="[2.0.0,2.1.0)"
# ordering="NONE"
# side="BOTH"

[[dependencies.${mod_id}]]
modId="tfmg"
versionRange="${tfmg_version_range}"
mandatory=true
ordering="AFTER"
side="BOTH"